spring.application.name: demo

# https://docs.spring.io/spring-boot/appendix/application-properties/index.html#appendix.application-properties.data

spring:
  cassandra:
    keyspace-name: "demo_ks"
    contact-points: "localhost:9042,localhost:9043,localhost:9044"
    local-datacenter: "datacenter1"
    ssl:
      enabled: false
    connection:
      connect-timeout: 5s
      init-query-timeout: 5s
    password: "dev0123"
    username: "devapp"
    request:
      consistency: ONE
      page-size: 100
      timeout: 30s
    schema-action: none
    session-name: demo